### ISSUE TITLE
Is the project maintained?

### ISSUE THREAD

**Issue by vladfaust** [maiha/crt.cr#14]
Hello,

I've checked your project and it's failing to build (or the specs failed) with the latest Crystal (0.26.1) or there are no any specs so the project cannot be validated to be up to date. Your project is in [Awesome Crystal](https://github.com/veelenga/awesome-crystal) list, so I'd like to ask if the project maintained?

I'll initiate a PR to remove your project from the list if you don't respond positively within 7 days.

I'm sorry if I'm wrong, because I've been checking many shards with automated script.

Thanks,
Vlad.

**Comment by maiha** [comment]
Hi, @vladfaust 
This requires `libncurses` as described in README, and it works with Crystal (0.26.1) in my environment where ubuntu-16.04 or higher.

Unfortunately, there was an error on travis. This seems to be a static link issue that occurs because travis uses too outdated ubuntu-14.04. I deleted the code about static link so that the test now passed.

Best regards,

**Comment by vladfaust** [comment]
Oh, my bad about the dependency. Sorry for disturbing! Note that you can set up daily/weekly tests on Travis so you'll receive a notification when the build begins to fail: https://docs.travis-ci.com/user/cron-jobs.

Thanks.

**Comment by maiha** [comment]
Hi, vladfaust 
Wow, I didn't know Cron Jobs! Thank you for the nice tips! 💯
